# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

# Install dependencies and ignore scripts if necessary
RUN npm install --ignore-scripts

# Copy source code
COPY . .

# Build the project
RUN npm run build

# Ensure the main file has execute permission
RUN chmod +x build/index.js

# Expose port if necessary (MCP uses stdio, so not needed)

# Command to run the server
CMD [ "node", "build/index.js" ]
